version: 2
services:
  prf-hotel-nodejs:
    build:
      context: service/
    ports:
    - "4000:4000"
  prf-hotel-angular:
    build:
      context: ui/
    ports:
    - "4000:4000"
  mongo:
    image: mongo:4.0
    ports:
    - "27017:27017"