version: 2
services:
  prf-hotel-angular:
    build:
      context: ui/
    ports:
    - "4200:4200"
    depends_on:
    - prf-hotel-nodejs
  prf-hotel-nodejs:
    build:
      context: service/
    ports:
    - "3000:3000"
    depends_on:
    - mongo
  mongo:
    image: mongo:4.0
    ports:
    - "27017:27017"