version: "2"
services:
  prf-hotel-mongo:
    image: mongo:4.0
    ports:
    - "27017:27017"
  prf-hotel-nodejs:
    build:
      context: service/
    ports:
    - "3000:3000"
    environment:
    - "EMAIL_USER="
    - "EMAIL_PASS="
    depends_on:
    - prf-hotel-mongo
  prf-hotel-angular:
    build:
      context: ui/
    ports:
    - "4200:4200"
    depends_on:
    - prf-hotel-nodejs
  prf-hotel-nginx:
    image: nginx:1.16.0
    volumes:
    - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
    - "8080:80"
    depends_on:
    - prf-hotel-angular